# Step 1. Data Cleaning

In [4]:
import csv
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats
from sklearn.utils.multiclass import unique_labels
from statistics import mean
import statistics

datas = pd.read_csv('./pp5i_train.gr.csv')
datas = datas.dropna()
#datas.head()

In [5]:
 
for i in range(1,70):
    ii = str(i)
    #datas[ii].to_list()
    #datas[ii].values.astype(int)
    datas[ii] = np.clip(datas[ii],a_min = 20,a_max = 16000)
#datas = datas.replace([19,16000],np.nan)
#datas = datas.replace([19,16000],0)
datas = datas.dropna()

# Step 2. Selecting top genes by class

# Remove from train data genes with fold differences

In [6]:
max_elements = datas.max(axis=1)
#print(max_elements)

min_elements = datas.min(axis=1)
#print(min_elements)
fold = max_elements/min_elements
#print(fold)

In [7]:
lowfold = []
for i,v in fold.items():
    if(v<2):
        #print(i,v)
        lowfold.append(i)
for i in lowfold:
    datas = datas.drop([i],axis=0)
print(datas.shape)
#datas = datas.loc[datas.max(axis=1) -datas.min(axis=1) > 2]

datas = datas.reset_index(drop=True)    #resetindex

(6413, 70)

# generate subsets with top class

In [8]:
train_class = open('pp5i_train_class.txt')
#classes.read()
classes = []
for i in train_class:
    classes.append(i)

'''
with open('pp5i_train.gr.csv', 'a') as f:
    writer = csv.writer(f)
    writer.writerow(classes)
'''
class_name = unique_labels(classes) 
EPD_index = []
JPA_index = []
MED_index = []
MGL_index = []
RHB_index = []

 
for i in range(1,len(classes)):
   
    if(classes[i] == 'EPD\n'):
        EPD_index.append(i)
    if(classes[i] == 'JPA\n'):
        JPA_index.append(i)
    if(classes[i] == 'MED\n'):
        MED_index.append(i)
    if(classes[i] == 'MGL\n'):
        MGL_index.append(i)
    if(classes[i] == 'RHB\n'):
        RHB_index.append(i)
        
print(datas)

              SNO    1    2    3    4    5    6    7    8    9  ...   60   61  \
0       A28102_at   30   46   31   31   26   28   35   29   21  ...   35   49
1     AB000114_at   22   31   20   20   26   24   29   20   23  ...   38   30
2     AB000115_at   29   70   20   20   20   20   20   20   20  ...   20  205
3     AB000220_at   76  208  244   39   85   23  634  159   50  ...   55  203
4     AB000409_at  167  211  179  119  161  166  228  267  260  ...  137  180
...           ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
6408    U58516_at  161  265  126  163  138  107   99  137  161  ...  410  238
6409    X06956_at   34   98   21   20   29   20   57   20   23  ...  101   25
6410    X83863_at  116  123  142  134  153  152  139  213  193  ...  117  203
6411    Z17240_at   44   43   44   38   42   46   46   52   32  ...   30   37
6412  M71243_f_at   30   31   28   21   26   29   32   57   34  ...   27   26

       62   63   64   65   66   67   68   69
0      31   51   71   68   77   56   41   38
1      22   24   20   21   22   25   21   20
2      20   61   62   35   30   65   32   25
3     152   53   28   30   31   31   27   20
4     107  147  170  131  132  158  164  172
...   ...  ...  ...  ...  ...  ...  ...  ...
6408  718  374  198  364  251  315  248  285
6409   39   56   26   34   45   27   46   61
6410  136  118  234  297  267  290  255  397
6411   39   20   47   39   42   36   44   38
6412   22   20   27   27   30   21   33   24

[6413 rows x 70 columns]

In [9]:
row_elements1 = [] 

for index, row in datas.iterrows():
    #print(index) # Output the index value of each row
    row_elements = [] 
    row_elements = datas.iloc[index]
    row_elements = row_elements.tolist()
    row_elements1.append(row_elements) 

EPD_T = []
JPA_T = []
MED_T = []
MGL_T = []
RHB_T = []

#MED
for value in range(0,len(row_elements1)):
    MED = []
    no_MED = []
    for i in range(1,len(row_elements1[value])):
        
        if(row_elements1[value][i] !=16000):
            exist_count = MED_index.count(i)
            if exist_count > 0:
                MED.append(row_elements1[value][i])
            else:
                no_MED.append(row_elements1[value][i])
     
    t,p = stats.ttest_ind(MED,no_MED)
    MED_T.append(abs(t))
    
#EPD
for value in range(0,len(row_elements1)):
    EPD = []
    no_EPD = []
    for i in range(1,len(row_elements1[value])):
        
        if(row_elements1[value][i] !=16000):
            exist_count = EPD_index.count(i)
            if exist_count > 0:
                EPD.append(row_elements1[value][i])
            else:
                no_EPD.append(row_elements1[value][i])
     
    t,p = stats.ttest_ind(EPD,no_EPD)
    EPD_T.append(abs(t))

#JPA
for value in range(0,len(row_elements1)):
    JPA = []
    no_JPA = []
    for i in range(1,len(row_elements1[value])):
        
        if(row_elements1[value][i] !=16000):
            exist_count = JPA_index.count(i)
            if exist_count > 0:
                JPA.append(row_elements1[value][i])
            else:
                no_JPA.append(row_elements1[value][i])
     
    t,p = stats.ttest_ind(JPA,no_JPA)
    JPA_T.append(abs(t))


#MGL
for value in range(0,len(row_elements1)):

    MGL = []
    no_MGL = []
    for i in range(1,len(row_elements1[value])):
        
        if(row_elements1[value][i] !=16000):
            exist_count = MGL_index.count(i)
            if exist_count > 0:
                MGL.append(row_elements1[value][i])
            else:
                no_MGL.append(row_elements1[value][i])

    t,p = stats.ttest_ind(MGL,no_MGL)
    MGL_T.append(abs(t))
    #print(MGL)


    
#RHB
for value in range(0,len(row_elements1)):
    RHB = []
    no_RHB = []
    for i in range(1,len(row_elements1[value])):
        
        if(row_elements1[value][i] !=16000):
            exist_count = RHB_index.count(i)
            if exist_count > 0:
                RHB.append(row_elements1[value][i])
            else:
                no_RHB.append(row_elements1[value][i])
     
    t,p = stats.ttest_ind(RHB,no_RHB)
    RHB_T.append(abs(t))

print(max(EPD_T))
print(max(JPA_T))
print(max(MED_T))
print(max(MGL_T))
print(max(RHB_T))

12.711130572248482
30.130451047298486
10.976900168041919
15.10815238395816
12.66302364217869

# TOP2

In [10]:
datas['EPD_T'] = EPD_T
datas['JPA_T'] = JPA_T
datas['MED_T'] = MED_T
datas['MGL_T'] = MGL_T
datas['RHB_T'] = RHB_T

EPD_top2 = datas.sort_values('EPD_T',ascending=False) 
EPD_top2 = EPD_top2.head(2)

JPA_top2 = datas.sort_values('JPA_T',ascending=False) 
JPA_top2 = JPA_top2.head(2)

MED_top2 = datas.sort_values('MED_T',ascending=False) 
MED_top2 = MED_top2.head(2)

MGL_top2 = datas.sort_values('MGL_T',ascending=False) 
MGL_top2 = MGL_top2.head(2)

RHB_top2= datas.sort_values('RHB_T',ascending=False) 
RHB_top2 = RHB_top2.head(2)

dftop2 = pd.concat((EPD_top2,JPA_top2,MED_top2,MGL_top2,RHB_top2),axis=0,join='inner')
#print(dftop2)

top2 = []

for i in range(0,20):
    if i <2:
        top2.append('EPD')
    elif i <4:
        top2.append('JPA')
    elif i <6:
        top2.append('MED')
    elif i <8:
        top2.append('MGL')
    elif i <10:
        top2.append('RHB')
    
#print(top2)
dftop2['Class'] = top2
dftop2 = dftop2.T
dftop2.to_csv('pp5i_train.top2.gr.csv',header=None)

In [11]:
'''
datas['EPD_T'] = EPD_T
datas['JPA_T'] = JPA_T
datas['MED_T'] = MED_T
datas['MGL_T'] = MGL_T
datas['RHB_T'] = RHB_T

EPD_top2 = datas.sort_values('EPD_T',ascending=False) 
EPD_top2 = EPD_top2.head(2)
EPD_top2 = EPD_top2['SNO']
EPD_top2 = EPD_top2.tolist()
EPD_top2=pd.DataFrame(EPD_top2)

JPA_top2 = datas.sort_values('JPA_T',ascending=False) 
JPA_top2 = JPA_top2.head(2)
JPA_top2 = JPA_top2['SNO']
JPA_top2 = JPA_top2.tolist()
JPA_top2=pd.DataFrame(JPA_top2)

MED_top2 = datas.sort_values('MED_T',ascending=False) 
MED_top2 = MED_top2.head(2)
MED_top2 = MED_top2['SNO']
MED_top2 = MED_top2.tolist()
MED_top2=pd.DataFrame(MED_top2)

MGL_top2 = datas.sort_values('MGL_T',ascending=False) 
MGL_top2 = MGL_top2.head(2)
MGL_top2 = MGL_top2['SNO']
MGL_top2 = MGL_top2.tolist()
MGL_top2=pd.DataFrame(MGL_top2)

RHB_top2= datas.sort_values('RHB_T',ascending=False) 
RHB_top2 = RHB_top2.head(2)
RHB_top2 = RHB_top2['SNO']
RHB_top2 = RHB_top2.tolist()
RHB_top2=pd.DataFrame(RHB_top2)

dftop2 = pd.concat((EPD_top2,JPA_top2,MED_top2,MGL_top2,RHB_top2),axis=0,join='inner')
#print(dftop2)

top2 = []

for i in range(0,10):
    if i <2:
        top2.append('EPD')
    elif i <4:
        top2.append('JPA')
    elif i <6:
        top2.append('MED')
    elif i <8:
        top2.append('MGL')
    elif i <10:
        top2.append('RHB')
    
#print(top2)
dftop2['Class'] = top2
#print(dftop2) 
dftop2 = dftop2.T
dftop2.to_csv('pp5i_train.top2.gr.csv',header=None)
'''

"\ndatas['EPD_T'] = EPD_T\ndatas['JPA_T'] = JPA_T\ndatas['MED_T'] = MED_T\ndatas['MGL_T'] = MGL_T\ndatas['RHB_T'] = RHB_T\n\nEPD_top2 = datas.sort_values('EPD_T',ascending=False) \nEPD_top2 = EPD_top2.head(2)\nEPD_top2 = EPD_top2['SNO']\nEPD_top2 = EPD_top2.tolist()\nEPD_top2=pd.DataFrame(EPD_top2)\n\nJPA_top2 = datas.sort_values('JPA_T',ascending=False) \nJPA_top2 = JPA_top2.head(2)\nJPA_top2 = JPA_top2['SNO']\nJPA_top2 = JPA_top2.tolist()\nJPA_top2=pd.DataFrame(JPA_top2)\n\nMED_top2 = datas.sort_values('MED_T',ascending=False) \nMED_top2 = MED_top2.head(2)\nMED_top2 = MED_top2['SNO']\nMED_top2 = MED_top2.tolist()\nMED_top2=pd.DataFrame(MED_top2)\n\nMGL_top2 = datas.sort_values('MGL_T',ascending=False) \nMGL_top2 = MGL_top2.head(2)\nMGL_top2 = MGL_top2['SNO']\nMGL_top2 = MGL_top2.tolist()\nMGL_top2=pd.DataFrame(MGL_top2)\n\nRHB_top2= datas.sort_values('RHB_T',ascending=False) \nRHB_top2 = RHB_top2.head(2)\nRHB_top2 = RHB_top2['SNO']\nRHB_top2 = RHB_top2.tolist()\nRHB_top2=pd.DataFrame(RHB_top2)\n\ndftop2 = pd.concat((EPD_top2,JPA_top2,MED_top2,MGL_top2,RHB_top2),axis=0,join='inner')\n#print(dftop2)\n\ntop2 = []\n\nfor i in range(0,10):\n    if i <2:\n        top2.append('EPD')\n    elif i <4:\n        top2.append('JPA')\n    elif i <6:\n        top2.append('MED')\n    elif i <8:\n        top2.append('MGL')\n    elif i <10:\n        top2.append('RHB')\n    \n#print(top2)\ndftop2['Class'] = top2\n#print(dftop2) \ndftop2 = dftop2.T\ndftop2.to_csv('pp5i_train.top2.gr.csv',header=None)\n"

# TOP4

In [12]:
EPD_top4 = datas.sort_values('EPD_T',ascending=False) 
EPD_top4 = EPD_top4.head(4)

JPA_top4 = datas.sort_values('JPA_T',ascending=False) 
JPA_top4 = JPA_top4.head(4)

MED_top4 = datas.sort_values('MED_T',ascending=False) 
MED_top4 = MED_top4.head(4)

MGL_top4 = datas.sort_values('MGL_T',ascending=False) 
MGL_top4 = MGL_top4.head(4)

RHB_top4= datas.sort_values('RHB_T',ascending=False) 
RHB_top4 = RHB_top4.head(4)

dftop4 = pd.concat((EPD_top4,JPA_top4,MED_top4,MGL_top4,RHB_top4),axis=0,join='inner')
#print(dftop4)

top4 = []

for i in range(0,20):
    if i <4:
        top4.append('EPD')
    elif i <8:
        top4.append('JPA')
    elif i <12:
        top4.append('MED')
    elif i <16:
        top4.append('MGL')
    elif i <20:
        top4.append('RHB')
    
#print(top4)
dftop4['Class'] = top4
dftop4 = dftop4.T
dftop4.to_csv('pp5i_train.top4.gr.csv',header=None)

# TOP6

In [13]:
EPD_top6 = datas.sort_values('EPD_T',ascending=False) 
EPD_top6 = EPD_top6.head(6)

JPA_top6 = datas.sort_values('JPA_T',ascending=False) 
JPA_top6 = JPA_top6.head(6)

MED_top6 = datas.sort_values('MED_T',ascending=False) 
MED_top6 = MED_top6.head(6)

MGL_top6 = datas.sort_values('MGL_T',ascending=False) 
MGL_top6 = MGL_top6.head(6)

RHB_top6= datas.sort_values('RHB_T',ascending=False) 
RHB_top6 = RHB_top6.head(6)

dftop6 = pd.concat((EPD_top6,JPA_top6,MED_top6,MGL_top6,RHB_top6),axis=0,join='inner')
#print(dftop6)

top6 = []

for i in range(0,30):
    if i <6:
        top6.append('EPD')
    elif i <12:
        top6.append('JPA')
    elif i <18:
        top6.append('MED')
    elif i <24:
        top6.append('MGL')
    elif i <30:
        top6.append('RHB')
    
#print(top6)
dftop6['Class'] = top6
dftop6 = dftop6.T

dftop6.to_csv('pp5i_train.top6.gr.csv',header=None)

# TOP8

In [101]:
EPD_top8 = datas.sort_values('EPD_T',ascending=False) 
EPD_top8 = EPD_top8.head(8)

JPA_top8 = datas.sort_values('JPA_T',ascending=False) 
JPA_top8 = JPA_top8.head(8)

MED_top8 = datas.sort_values('MED_T',ascending=False) 
MED_top8 = MED_top8.head(8)

MGL_top8 = datas.sort_values('MGL_T',ascending=False) 
MGL_top8 = MGL_top8.head(8)

RHB_top8= datas.sort_values('RHB_T',ascending=False) 
RHB_top8 = RHB_top8.head(8)

dftop8 = pd.concat((EPD_top8,JPA_top8,MED_top8,MGL_top8,RHB_top8),axis=0,join='inner')
#print(dftop8)
top8 = []

for i in range(0,40):
    if i <8:
        top8.append('EPD')
    elif i <16:
        top8.append('JPA')
    elif i <24:
        top8.append('MED')
    elif i <32:
        top8.append('MGL')
    elif i <40:
        top8.append('RHB')
    
#print(top8)
dftop8['Class'] = top8
dftop8 = dftop8.T
dftop8.to_csv('pp5i_train.top8.gr.csv',header=None)

# TOP10

In [102]:
EPD_top10 = datas.sort_values('EPD_T',ascending=False) 
EPD_top10 = EPD_top10.head(10)

JPA_top10 = datas.sort_values('JPA_T',ascending=False) 
JPA_top10 = JPA_top10.head(10)

MED_top10 = datas.sort_values('MED_T',ascending=False) 
MED_top10 = MED_top10.head(10)

MGL_top10 = datas.sort_values('MGL_T',ascending=False) 
MGL_top10 = MGL_top10.head(10)

RHB_top10= datas.sort_values('RHB_T',ascending=False) 
RHB_top10 = RHB_top10.head(10)

dftop10 = pd.concat((EPD_top10,JPA_top10,MED_top10,MGL_top10,RHB_top10),axis=0,join='inner')
#print(dftop10)
top10 = []

for i in range(0,50):
    if i <10:
        top10.append('EPD')
    elif i <20:
        top10.append('JPA')
    elif i <30:
        top10.append('MED')
    elif i <40:
        top10.append('MGL')
    elif i <50:
        top10.append('RHB')
    
#print(top10)
dftop10['Class'] = top10

dftop10 = dftop10.T
dftop10.to_csv('pp5i_train.top10.gr.csv',header=None)

# TOP12

In [103]:
EPD_top12 = datas.sort_values('EPD_T',ascending=False) 
EPD_top12 = EPD_top12.head(12)

JPA_top12 = datas.sort_values('JPA_T',ascending=False) 
JPA_top12 = JPA_top12.head(12)

MED_top12 = datas.sort_values('MED_T',ascending=False) 
MED_top12 = MED_top12.head(12)

MGL_top12 = datas.sort_values('MGL_T',ascending=False) 
MGL_top12 = MGL_top12.head(12)

RHB_top12= datas.sort_values('RHB_T',ascending=False) 
RHB_top12 = RHB_top12.head(12)

dftop12 = pd.concat((EPD_top12,JPA_top12,MED_top12,MGL_top12,RHB_top12),axis=0,join='inner')
#print(dftop12)
top12 = []

for i in range(0,60):
    if i <12:
        top12.append('EPD')
    elif i <24:
        top12.append('JPA')
    elif i <36:
        top12.append('MED')
    elif i <48:
        top12.append('MGL')
    elif i <60:
        top12.append('RHB')
    
#print(top12)
dftop12['Class'] = top12
dftop12 = dftop12.T
dftop12.to_csv('pp5i_train.top12.gr.csv',header=None)

# TOP15

In [104]:
EPD_top15 = datas.sort_values('EPD_T',ascending=False) 
EPD_top15 = EPD_top15.head(15)

JPA_top15 = datas.sort_values('JPA_T',ascending=False) 
JPA_top15 = JPA_top15.head(15)

MED_top15 = datas.sort_values('MED_T',ascending=False) 
MED_top15 = MED_top15.head(15)

MGL_top15 = datas.sort_values('MGL_T',ascending=False) 
MGL_top15 = MGL_top15.head(15)

RHB_top15= datas.sort_values('RHB_T',ascending=False) 
RHB_top15 = RHB_top15.head(15)

dftop15 = pd.concat((EPD_top15,JPA_top15,MED_top15,MGL_top15,RHB_top15),axis=0,join='inner')
#print(dftop15)
top15 = []

for i in range(0,75):
    if i <15:
        top15.append('EPD')
    elif i <30:
        top15.append('JPA')
    elif i <45:
        top15.append('MED')
    elif i <60:
        top15.append('MGL')
    elif i <75:
        top15.append('RHB')
    
#print(top15)
dftop15['Class'] = top15
dftop15 = dftop15.T
dftop15.to_csv('pp5i_train.top15.gr.csv',header=None)

# TOP20

In [105]:
EPD_top20 = datas.sort_values('EPD_T',ascending=False) 
EPD_top20 = EPD_top20.head(20)

JPA_top20 = datas.sort_values('JPA_T',ascending=False) 
JPA_top20 = JPA_top20.head(20)

MED_top20 = datas.sort_values('MED_T',ascending=False) 
MED_top20 = MED_top20.head(20)

MGL_top20 = datas.sort_values('MGL_T',ascending=False) 
MGL_top20 = MGL_top20.head(20)

RHB_top20= datas.sort_values('RHB_T',ascending=False) 
RHB_top20 = RHB_top20.head(20)

dftop20 = pd.concat((EPD_top20,JPA_top20,MED_top20,MGL_top20,RHB_top20),axis=0,join='inner')
#print(dftop20)
top20 = []

for i in range(0,100):
    if i <20:
        top20.append('EPD')
    elif i <40:
        top20.append('JPA')
    elif i <60:
        top20.append('MED')
    elif i <80:
        top20.append('MGL')
    elif i <100:
        top20.append('RHB')
    
#print(top20)
dftop20['Class'] = top20
dftop20 = dftop20.T
dftop20.to_csv('pp5i_train.top20.gr.csv',header=None)

# TOP25

In [106]:
EPD_top25 = datas.sort_values('EPD_T',ascending=False) 
EPD_top25 = EPD_top25.head(25)

JPA_top25 = datas.sort_values('JPA_T',ascending=False) 
JPA_top25 = JPA_top25.head(25)

MED_top25 = datas.sort_values('MED_T',ascending=False) 
MED_top25 = MED_top25.head(25)

MGL_top25 = datas.sort_values('MGL_T',ascending=False) 
MGL_top25 = MGL_top25.head(25)

RHB_top25= datas.sort_values('RHB_T',ascending=False) 
RHB_top25 = RHB_top25.head(25)

dftop25 = pd.concat((EPD_top25,JPA_top25,MED_top25,MGL_top25,RHB_top25),axis=0,join='inner')
#print(dftop25)
top25 = []

for i in range(0,125):
    if i <25:
        top25.append('EPD')
    elif i <50:
        top25.append('JPA')
    elif i <75:
        top25.append('MED')
    elif i <100:
        top25.append('MGL')
    elif i <125:
        top25.append('RHB')
    
#print(top25)
dftop25['Class'] = top25
dftop25 = dftop25.T
dftop25.to_csv('pp5i_train.top25.gr.csv',header=None)

# TOP30

In [107]:
EPD_top30 = datas.sort_values('EPD_T',ascending=False) 
EPD_top30 = EPD_top30.head(30)

JPA_top30 = datas.sort_values('JPA_T',ascending=False) 
JPA_top30 = JPA_top30.head(30)

MED_top30 = datas.sort_values('MED_T',ascending=False) 
MED_top30 = MED_top30.head(30)

MGL_top30 = datas.sort_values('MGL_T',ascending=False) 
MGL_top30 = MGL_top30.head(30)

RHB_top30= datas.sort_values('RHB_T',ascending=False) 
RHB_top30 = RHB_top30.head(30)

dftop30 = pd.concat((EPD_top30,JPA_top30,MED_top30,MGL_top30,RHB_top30),axis=0,join='inner')
#print(dftop30)
top30 = []

for i in range(0,150):
    if i <30:
        top30.append('EPD')
    elif i <60:
        top30.append('JPA')
    elif i <90:
        top30.append('MED')
    elif i <120:
        top30.append('MGL')
    elif i <150:
        top30.append('RHB')
    
#print(top30)
dftop30['Class'] = top30
dftop30 = dftop30.T
dftop30.to_csv('pp5i_train.top30.gr.csv',header=None)

In [108]:
T30 = pd.read_csv('./pp5i_train.top30.gr.csv')
row30 = T30.columns #
print(row30)

 
set_row30=set(row30)
#Set generates an iteratable object whose elements are unordered and not repeated
if len(set_row30)==len(row30):
    print('No Duplicate elements in the list')
else:
    print('Duplicate elements in the list')

Index(['SNO', 'X03363_s_at', 'X05908_at', 'U15131_at', 'L49054_at',
       'M31516_s_at', 'U53204_at', 'L25878_s_at', 'U90913_at', 'X72964_at',
       ...
       'X13839_at', 'L14565_at', 'L11353_at', 'X54304_at', 'M23114_at',
       'U21858_at', 'X95325_s_at', 'U72263_s_at', 'U96131_at', 'M24069_at'],
      dtype='object', length=151)
No Duplicate elements in the list